jenkins:
  systemMessage: "CloudBees Jenkins Team local demo environment with sample-rest-server job configured as code."
  numExecutors: 0
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  agentProtocols:
    - 'JNLP4-connect'
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true
  securityRealm:
    local:
      users:
        - id: ${JENKINS_USER}
          password: ${JENKINS_PASSWORD}
  remotingSecurity:
    enabled: true
  slaveAgentPort: 50000
security:
  remotingCLI:
    enabled: false
  sshd:
    port: 2222
unclassified:
  location:
    url: http://localhost:9090
  globalLibraries:
    libraries:
      - name: "github.com/cloudy-demos/pipeline-libraries"
        defaultVersion: master
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/cloudy-demos/pipeline-libraries.git"
jobs:
  - script : >
      multibranchPipelineJob('sample-rest-server') {
        branchSources {
          git {
            id('sample-rest-server-branchSource')
            remote("https://github.com/cloudy-demos/sample-rest-server.git")
            includes('*')
          }
        }
      }
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: sonar
              username: ${SONAR_USER}
              password: ${SONAR_PASSWORD}
          - usernamePassword:
              scope: GLOBAL
              id: dockerhub
              username: ${DOCKERHUB_USER}
              password: ${DOCKERHUB_PASSWORD}
