# Image installs with latest Java 8 OpenJDK on Alpine Linux
FROM schottsfired/general-purpose-jenkins-agent:latest

LABEL app-name="cjt-demo-environment"

# Download the latest Jenkins swarm client with curl
# Browse all versions here: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/
RUN curl -O https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.15/swarm-client-3.15.jar